Update pyarrow to 0.17.0
- Remove hdfs3 support because current code fails with in pyarrow 0.17.0
"TypeError: connect() got an unexpected keyword argument 'driver'"

- All changes are backwards compatible as the driver arg will just take the default arg 'libhdfs'

- Related arrow commit where hdfs3 is deactivated
(see https://github.com/apache/arrow/commit/4e53749097ba687afd5e000067925def2e2802c9)

- Prepare next commit adding viewfs support
(see https://github.com/apache/arrow/pull/5957)